
server:
  port: 9091
spring:
  application:
    name: itcast-consumer
eureka:
  client:
    service-url: # EurekaServer\u5730\u5740
      defaultZone: http://127.0.0.1:10086/eureka
  registry-fetch-interval-seconds: 5  # \u6BCF\u96945\u79D2\u4F1A\u91CD\u65B0\u83B7\u53D6\u5E76\u66F4\u65B0\u6570\u636E

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: #6000 设置hystrix的超时时间为6000ms
feign:
  hystrix:
    enabled: true
